### ISSUE TITLE
Vue Full Calendar module require `jquery` error - not confirmed.

### ISSUE THREAD

**Issue by deepenpatel19** [fullcalendar/fullcalendar-vue#69]
Yesterday, I created one build with full calendar - v3.10.1 in Vue and deployed on the server.
Then, I have seen something wrong with full calendar library. 
Error in web console something like this,
`
Uncaught Error: Cannot find module "jquery"
`

After click on the error reference point, I can see the error from full calendar component.
```
/*!
 * FullCalendar v3.10.1
 * Docs & License: https://fullcalendar.io/
 * (c) 2019 Adam Shaw
 */
(function webpackUniversalModuleDefinition(root, factory) {
	if(true)
		module.exports = factory(__webpack_require__(2), __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"jquery\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())));
	else if(typeof define === 'function' && define.amd)
		define(["moment", "jquery"], factory);
	else if(typeof exports === 'object')
		exports["FullCalendar"] = factory(require("moment"), require("jquery"));
	else
		root["FullCalendar"] = factory(root["moment"], root["jQuery"]);

```

As I can see it require `jquery` and `moment` library. so, One solution maybe I have to add `jquery` in dependencies. 

It would be great if someone help to solve this or share an alternate solution.

Thanks.

**Comment by deepenpatel19** [comment]
I tried after adding jquery in dependency and it works.
