### ISSUE TITLE
Global.vue is not a function

### ISSUE THREAD

**Issue by sarfarazansari** [fullcalendar/fullcalendar-vue#187]
### Bug Report
After Updating VUE JS version to 2.6.14
full calendar vue library throws and error `global vue is not a function`
it is somehow similar to window.vue.
<img width="650" alt="image" src="https://user-images.githubusercontent.com/3416989/185092755-8444a9e6-abf1-48d8-94a7-79e642bfffac.png">

the above lines causing the issue.
If we remove those lines issue has been solved

here is the error
```
TypeError: GlobalVue.use is not a function
at eval (webpack-internal:///./node_modules/@fullcalendar/vue/dist/main.js:449)
at Module../node_modules/@fullcalendar/vue/dist/main.js (:5001/9.js:164)
at webpack_require (app.js:833)
at fn (app.js:130)
at eval (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Teacher_Manage/Teacher_Time/EditForm.vue?vue&type=script&lang=js&:3)
at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Teacher_Manage/Teacher_Time/EditForm.vue?vue&type=script&lang=js& (:5001/38.js:23)
at webpack_require (app.js:833)
at fn (app.js:130)
at eval (webpack-internal:///./src/views/Teacher_Manage/Teacher_Time/EditForm.vue?vue&type=script&lang=js&:2)
```

### package.json details

<img width="601" alt="image" src="https://user-images.githubusercontent.com/3416989/185093437-9f8c0b41-c248-4891-a3a2-3379a5e19a51.png">

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
